---
title: "Report Exercise Chapter 8"
author: "Fabio Jakob 20-107-876"
date: "2023-04-17"
output: html_document
---
read the data with readr
```{r}
library(readr)
df_for_stepwise_regression <- read_csv('C:/Users/fabio.LAPTOP-FR4VQFHF/Documents/agds_report_fabiojakob/Data/df_for_stepwise_regression.csv')
View(df_for_stepwise_regression)

#handle the NA-Values
df_for_stepwise_regression <- na.omit(df_for_stepwise_regression)

#make the GPP the last column in the table
df_for_stepwise_regression$GPP_NT_VUT_REF_new <- df_for_stepwise_regression$GPP_NT_VUT_REF

df_for_stepwise_regression$GPP_NT_VUT_REF <- NULL

```
1. Evaluation of all bivariate models

implementing steps 1-3 of the algorithm.
```{r}

# create a list to store R-squared values for each model
rsquared_list <- list()

# loop over each predictor variable
for (predictor in names(df_for_stepwise_regression)[1:(ncol(df_for_stepwise_regression)-1)]) {
  
  # fit regression model with p predictors
  model_1 <- lm(GPP_NT_VUT_REF_new ~ get(predictor), data = df_for_stepwise_regression)
  
  # compute R-squared and store in list
  rsquared <- summary(model_1)$r.squared
  rsquared_list[[predictor]] <- rsquared
}

# find predictor variable with highest R-squared
best_predictor <- names(rsquared_list)[which.max(unlist(rsquared_list))]


# fit best model and compute AIC
best_model <- lm(GPP_NT_VUT_REF_new ~ get(best_predictor), data = df_for_stepwise_regression)
best_aic <- AIC(best_model)


# plot R-squared values for each predictor
plot(unlist(rsquared_list), xlab = "", ylab = "R-Squared Values")
axis(side = 1,at = seq(1, 16, 1), labels = names(rsquared_list), las = 2,)
```
2. manual implementation of stepwise forward regression:

```{r}
selected <- c()
aic <- Inf
predictors <- c("siteid", "TIMESTAMP", "TA_F", "SW_IN_F", "LW_IN_F", "VPD_F", "PA_F", "P_F", "WS_F", "TA_F_MDS", "SW_IN_F_MDS", "LW_IN_F_MDS", "VPD_F_MDS", "CO2_F_MDS","PPFD_IN", "USTAR")
```


```{r}
while (length(predictors)> 0) {
  
  r <- rep(NA, length(predictors))
  
  for (i in 1:length(predictors)) {
    
    formula <- paste("GPP_NT_VUT_REF_new", paste(predictors[i]), collapse = "+", sep     = "~")
    model <- lm(formula, df_for_stepwise_regression)
  
    r[i] <- summary(model)$r.squared
  }
   
  min_r <- max(r)
  min_index <- which(r == min_r)
  best_predictor <- predictors[min_index]
    
 
  
  if (length(selected) == 0) {
  formula <- paste("GPP_NT_VUT_REF_new", best_predictor, sep = "~")
  } else {
  formula <- paste("GPP_NT_VUT_REF_new", paste(selected, collapse = "+"), sep = "~")
  }

  best_model <- lm(formula, df_for_stepwise_regression)

  best_aic <- AIC(best_model)
  
  
  
  if (best_aic < aic) {
    # Compare to current minimum AIC value
    selected <- c(selected, best_predictor)
    aic <- best_aic
  } else {
    break
  }
  


  predictors <- predictors[-min_index]
}


```

```{r}
formula <- paste("GPP_NT_VUT_REF_new", paste(selected, collapse = "+"), sep = "~")
model <- lm(formula, df_for_stepwise_regression)

summary(model)
```

```{r}
df_for_stepwise_regression$y_pred <- predict(model, newdata = df_for_stepwise_regression)

library(ggplot2)
ggplot(df_for_stepwise_regression, aes(x = GPP_NT_VUT_REF_new, y = y_pred)) +
  geom_point() + geom_smooth(method = "lm", se = FALSE, color = "red") +
  labs(x = "Actual Values", y = "Predicted Values", title = "Stepwise Forward Regression Results")
```
The visualization shows that the model is not that good in predicting the GPP values.









